/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface components {
  schemas: {
    /**
     * an object describing xur's location, or null if xur is not visiting the specified day
     */
    XurLocation: {
      /**
       * a simple lowercase string, one of the following:
       * edz, titan, nessus, io, tower
       */
      location: string;
      /**
       * a hash corresponding to the DestinyDestinationDefinition for this
       * location
       */
      destinationHash: number;
      /**
       * an index pointing to the DestinyBubbleDefinition for this location,
       * within DestinyDestinationDefinition.bubbles
       */
      bubbleIndex: number;
      /**
       * the english display name for the DestinyDestinationDefinition, i.e.
       * "European Dead Zone"
       */
      destinationName: string;
      /**
       * the english display name for the DestinyBubbleDefinition, i.e.
       * "Winding Cove"
       */
      bubbleName: string;
    } | null;
  };
}
